# Generated by Django 5.2.15 on 2026-06-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_prime',
            field=models.BooleanField(default=False),
        ),
    ]
