# Generated by Django 5.2.15 on 2026-06-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_prime',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
