# Generated by Django 5.2.15 on 2026-06-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_is_prime_remove_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_prime',
            field=models.BooleanField(default=False),
        ),
    ]
